image: 'silquenarmo/dex-plutus-dev:1.4'

stages:
  - lint
  - build
  - test

lint_uniswap_json_api:
  stage: lint
  script:
    - nix-shell /build/default.nix --run 'hlint uniswap-json-api'

lint_uniswap:
  stage: lint
  script:
    - nix-shell /build/default.nix --run 'hlint uniswap'

build_uniswap_json_api:
  stage: build
  script:
    - nix-shell /build/default.nix --run 'cd uniswap-json-api && cabal build'

build_uniswap:
  stage: build
  script:
    - nix-shell /build/default.nix --run 'cd uniswap && cabal build'

uniswap_json_api_spec:
  stage: test
  script:
    - nix-shell /build/default.nix --run 'cd uniswap-json-api && cabal test'

uniswap_json_api_spec:
  stage: test
  script:
    - nix-shell /build/default.nix --run 'cd uniswap && cabal test'
